backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Test File"
        name: "testfile"
        file: "content/site.json"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
